server:
  port: 8081

spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: client-processing
    password: securepassword
    pooled: false
  jms:
    template:
      default-destination: client.processing.queue