server:
  port: 8081

spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
    pooled: false
  jms:
    template:
      default-destination: client.processing.queue