
server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/client_db?currentSchema=client_info
    username: client
    password: client
  jpa:
    hibernate:
      ddl-auto: create-drop
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
    pooled: false
  jms:
    template:
      default-destination: client.processing.queue