server:
  port: 8084

spring:
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin
    pooled: false
  jms:
    template:
      default-destination: client.processing.queue
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

app:
  wiremock:
    url: http://wiremock:8080